spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-micro-user
    username: postgres
    password: Santoshrai@123

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081